defaults:
  - hydra/launcher: slurm

hydra:
  run:
    dir: /h/nng/hydra/${hydra.job.name}/${now:%Y-%m-%d_%H-%M-%S-%N}
  sweep:
    dir: /h/nng/hydra/${hydra.job.name}/${now:%Y-%m-%d_%H-%M-%S-%N}
    subdir: ${hydra.job.num}

venv: robust
wait: false
extra: ~
next_day: ~
max_running: -1
max_pending: -1

slurm:
  cpus_per_task: eval:4*int("${slurm.gres}"[-1])
  dependency: ~
  exclude: gpu080,gpu115,gpu021,gpu060,gpu139,gpu108
  gres: gpu:1
  job_name:
    - eval:sys.argv[0][:-3].split('/')[-1]
    - ${extra}
  mem: eval:str(20*int("${slurm.gres}"[-1]))+'G'
  nodes: 1
  ntasks_per_node: 1
  open_mode: append
  partition: rtx6000,t4v2,t4v1,p100
  account: ~
  qos: normal

