train:
  arch: lstm_classifier
  num_classes: 5
  lr: 1e-04
  lr_scheduler: inverse_sqrt
  warmup_updates: 500
  max_epoch: 10
  max_sentences: 8
  update_freq: 32
  max_positions: ~
  encoder_layers: 1
  dropout: 0.3
  pooler_dropout: 0.1
