train:
  arch: fconv_classifier
  num_classes: 5
  lr: 1e-03
  lr_scheduler: inverse_sqrt
  warmup_updates: 500
  max_epoch: 10
  max_sentences: 8
  update_freq: 32
  max_positions: ~
  dropout: 0.2
  pooler_dropout: 0.2

extra: conv

eval:
  model:
    date: ~
    data: aws
  data: aws
