train:
  arch: transformer
  task: translation
  share_decoder_input_output_embed: true
  lr: 5e-4 
  lr_scheduler: inverse_sqrt
  warmup_updates: 4000
  dropout: 0.3
  weight_decay: 0.0001
  criterion: label_smoothed_cross_entropy
  label_smoothing: 0.1
  max_tokens: 4096
  eval_bleu: true
  eval_bleu_args: '{"beam": 5, "max_len_a": 1.2, "max_len_b": 10}'
  eval_bleu_detok: moses
  eval_bleu_remove_bpe: true
  eval_bleu_print_samples: true
  best_checkpoint_metric: bleu
  random_token_prob: ~
  init_token : ~
  leave_unmasked_prob: ~
  mask_prob: ~
  max_positions: ~
  random_token_prob: ~
  separator_token: ~
  max_epoch: 100

extra: ${train.augment}
